### PR TITLE
Fix labels being removed when other fields are updated but labels is not changed.

### LINKED ISSUE #104: Original label is removed upon saving a previously pulled story
Hey,
not sure if i'm using the gem in the right way.

these are they steps:

```
client = TrackerApi::Client.new token: token
project = client.project project_id
story = project.story story_id

story.create_comment text: comment_text
story.estimate = estimation
story.current_state = new_state
story.save
```

- comment is created
- new state is set
- estimate is changed

but also the original label is gone. btw, the label also represents an epic.

i'm following a quite procedural approach here, so maybe there's the problem?

### PR DESCRIPTION
**Pull request by forest**
Fixes #104

### CODE REVIEW

File: lib/tracker_api/resources/story.rb [hunk 1]
```diff
@@ -21,7 +21,7 @@ class Story
       attribute :integration_id, Integer
       attribute :kind, String
       attribute :label_ids, [Integer]
-      attribute :labels, [Label]
+      attribute :labels, [Label], default: nil
```
Comment (forest) [inline lib/tracker_api/resources/story.rb]: The reason defaulting the labels attribute fixes this issue has to do with the `UpdateRepersenter` class that specifies that an empty collection should be rendered. This is done so that if you want to clear all the labels you can set `story.labels = []` and it will get rendered to json instead of ignored. 
`collection :labels, class: Label, decorator: Label::UpdateRepresenter, render_empty: true`

Here is some example code and output that shows the behavior.
```
st = Story.new(self.dirty_attributes)
st.labels
>nil
UpdateRepresenter.new(Story.new(st.dirty_attributes)).to_json
>{}
st.labels = []
[]
UpdateRepresenter.new(Story.new(st.dirty_attributes)).to_json
{"labels":[]}
```

Comment (forest) [inline lib/tracker_api/resources/story.rb]: @whysthatso does this make sense?

I am actually working on another branch that will remove the existing dirty tracking. It has caused way more issues than it is worth. IMO.
